name: OpenTofu Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Required for AWS OIDC authentication
permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-west-2
  STATE_BUCKET: github-oidc-sudo-whodo-test-tofu-state
  TOFU_VERSION: 1.8.5

jobs:
  tofu:
    name: OpenTofu Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-OpenTofu

      - name: Verify AWS credentials
        run: |
          aws sts get-caller-identity
          echo "AWS credentials configured successfully"

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ env.TOFU_VERSION }}

      - name: OpenTofu Format Check
        id: fmt
        run: tofu fmt -check -recursive
        continue-on-error: true

      - name: OpenTofu Init
        id: init
        run: |
          tofu init \
            -backend-config="bucket=${{ env.STATE_BUCKET }}" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="encrypt=true"

      - name: OpenTofu Validate
        id: validate
        run: tofu validate -no-color

      - name: OpenTofu Plan
        id: plan
        run: |
          tofu plan \
            -var="bucket_name=${{ secrets.BUCKET_NAME }}" \
            -var="aws_region=${{ env.AWS_REGION }}" \
            -no-color

      - name: Display Plan Summary
        if: always()
        run: |
          echo "✅ OpenTofu plan completed successfully!"
          echo "Review the plan output above to see what resources will be created."
